import { serve } from 'https://deno.land/std@0.168.0/http/server.ts'

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
}

serve(async (req) => {
  // Handle CORS preflight
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders })
  }

  try {
    const { player_phone, player_name, fixture_id, opponent, fixture_date, venue } = await req.json()

    // Validate inputs
    if (!player_phone || !fixture_id) {
      return new Response(
        JSON.stringify({ error: 'Missing required fields: player_phone, fixture_id' }),
        { headers: { ...corsHeaders, 'Content-Type': 'application/json' }, status: 400 }
      )
    }

    // Get Twilio credentials from environment
    const accountSid = Deno.env.get('TWILIO_ACCOUNT_SID')
    const authToken = Deno.env.get('TWILIO_AUTH_TOKEN')
    const twilioWhatsappNumber = Deno.env.get('TWILIO_WHATSAPP_NUMBER')

    if (!accountSid || !authToken || !twilioWhatsappNumber) {
      console.error('Missing Twilio configuration')
      return new Response(
        JSON.stringify({ error: 'Twilio credentials not configured. Please set TWILIO_ACCOUNT_SID, TWILIO_AUTH_TOKEN, and TWILIO_WHATSAPP_NUMBER' }),
        { headers: { ...corsHeaders, 'Content-Type': 'application/json' }, status: 500 }
      )
    }

    // Format phone number to WhatsApp format
    const formattedPhone = `whatsapp:${player_phone}`

    // Create message body
    const fixtureDate = new Date(fixture_date).toLocaleDateString('en-GB', {
      weekday: 'short',
      month: 'short',
      day: 'numeric',
      year: 'numeric',
      hour: '2-digit',
      minute: '2-digit'
    })

    const messageBody = `Hi ${player_name || 'Player'}! 🏏

Fixture Availability Poll:
📍 *${opponent}* vs Northolt Manor CC
📅 ${fixtureDate}
🏟️ ${venue}

*Please Reply:*
• YES - If you're available
• NO - If you're not available
• MAYBE - If you're unsure

Your response helps us plan the team! 🙌

(Auto-generated by NMCC Fixture System)`

    console.log(`Sending WhatsApp to ${formattedPhone}`)

    // Prepare Twilio request
    const auth = btoa(`${accountSid}:${authToken}`)
    const params = new URLSearchParams()
    params.append('From', twilioWhatsappNumber)
    params.append('To', formattedPhone)
    params.append('Body', messageBody)

    // Send via Twilio API
    const response = await fetch(
      `https://api.twilio.com/2010-04-01/Accounts/${accountSid}/Messages.json`,
      {
        method: 'POST',
        headers: {
          'Authorization': `Basic ${auth}`,
          'Content-Type': 'application/x-www-form-urlencoded'
        },
        body: params.toString()
      }
    )

    const data = await response.json()

    if (!response.ok) {
      console.error('Twilio error:', data)
      return new Response(
        JSON.stringify({ error: 'Failed to send WhatsApp message', details: data }),
        { headers: { ...corsHeaders, 'Content-Type': 'application/json' }, status: 400 }
      )
    }

    console.log(`Successfully sent WhatsApp message: ${data.sid}`)

    return new Response(
      JSON.stringify({ 
        success: true, 
        message_sid: data.sid,
        message: 'WhatsApp poll sent successfully'
      }),
      { headers: { ...corsHeaders, 'Content-Type': 'application/json' }, status: 200 }
    )
  } catch (error) {
    console.error('Error sending WhatsApp message:', error)
    return new Response(
      JSON.stringify({ error: error.message }),
      { headers: { ...corsHeaders, 'Content-Type': 'application/json' }, status: 500 }
    )
  }
})
